import pygame as pg

KEY_ACCELERATE = pg.K_a
KEY_BRAKE = pg.K_s
KEY_TURN_LEFT = pg.K_LEFT
KEY_TURN_RIGHT = pg.K_RIGHT
KEY_FLIP_CAR = pg.K_f
KEY_USE_ABILITY = pg.K_SPACE
KEY_CAR_HORN = pg.K_h

ALL_KEYS = [KEY_ACCELERATE, KEY_BRAKE, KEY_CAR_HORN, KEY_FLIP_CAR,
            KEY_TURN_LEFT, KEY_TURN_RIGHT, KEY_USE_ABILITY]
